- name: multiplays1
  host: local
  connection: local
  tasks:
    - name: task1
      ansible.builtin.debug:
      msg: hello harsha

- name: multiplays2
  host: local
  connection: local
  tasks:
    - name: task2
      ansible.builtin.debug:
      msg: hello janith