- name: install  and run nginx
  hosts: web
  become: yes # -b its like root access sudo
  vars:
  web_pkg: nginx

  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    when: OS family == "RedHat"

  - name: Start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      when: OS family == "RedHat"