- name: odd r even
  hosts: local
  connection: local
  vars:
    nums: 10
 
  tasks:
  - name: even
    ansible.builtin.debug:
      msg: "{{nums}} is even"
    when: (nums | int) % 2 == 0

  - name: odd 
    ansible.builtin.debug:
      msg: "{{nums}} is odd"
    when: (nums | int) % 2 != 0
    