- name: install multiple package
  hosts: local
  connection: local
  tasks:
  - name: install packages using loops
    ansible.builtin.package:
      name: "{{ iteam }}"
      state: present
    loop:
    - git
    - curl
    - wget
