- name: install multiple package
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages using loops
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - curl
      - wget
