- name: odd r even
  hosts: local
  connection: local
  vars:
    num=10
 
  tasks:
  - name: even
    ansible.builtin.debug:
      msg: "{{num}} is even"
    when: num % 2

  - name: odd 
    ansible.builtin.debug:
      msg: "{{num}} is even"
    when: num % 2