- name: install multiple package
  hosts: local
  connection: local
  tasks:
  - name: install packages using loops
    ansible.builtin.packages:
      name: "{{ iteam }}"
      satae: present
  loop:
  - git
  - curl
  - wget
