- name: less than or greater than
  hosts: local
  connection: local # -b its like root access sudo
  vars:
    my_number1: 8
  #my_number2: 10

  tasks:
  - name: greater than
    ansible.builtin.debug:
      msg: "the {{my_number1}} is greater 10"
    when: my_number1 > 10

  - name: less than
    ansible.builtin.debug:
      msg: "the {{my_number1}} is less 10"
    when: my_number1 < 10